version: "3.7"

services:
  chibisafe:
    image: ghcr.io/harmonyvt/harmonyspring:latest
    container_name: harmonyspring
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./database:/home/node/harmonyspring/database:rw
      - ./uploads:/home/node/harmonyspring/uploads:rw
      - ./logs:/home/node/harmonyspring/logs:rw
    ports:
      - 731:8000
    restart: unless-stopped
